CurhatMe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('testimoni/', include('testimoni.urls'))
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('reply/', views.reply, name='reply'),
    path('replies/', views.postreply, name='postreply'),
]

testimoni/urls.py
from django.urls import path
from . import views

app_name = 'testimoni'

urlpatterns = [
    path('', views.testimoni, name='testimoni'),
]

homepage/models.py
from django.db import models
# from datetime import datetime, date

class Reply(models.Model):
    
    reply = models.CharField(max_length=300)
    like = models.IntegerField(default=0)

    def __str__(self):
        return self.activity

    

testimoni/models.py
from django.db import models

# Create your models here.
class Curhat(models.Model):
    nama = models.CharField(max_length = 10, default="Unknown")
    testi = models.CharField(max_length = 100, default="Unknown")

homepage/forms.py
from django import forms
from .models import Reply

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['reply']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

testimoni/forms.py
from django import forms


# class CurhatForm(forms.Form):
#     curhat = forms.CharField(widget=forms.Textarea, max_length=100)
#     taks = forms.CharField(widget=forms.Textarea, max_length=100)
#     searchcolumn = forms.CharField(widget=forms.Textarea, max_length=100)

homepage/views.py
from django.shortcuts import render, redirect
from .models import Reply
from .import forms

# Create your views here.
def homepage(request):
    return render(request, 'homepage.html')

def postreply(request):
    postreply = Reply.objects.all()
    return render(request, 'postreply.html', {'postreply':postreply})

def reply(request):
    if request.method == 'POST':
        form = forms.ReplyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:postreply')

    else:
        form = forms.ReplyForm()
    return render(request, 'reply.html', {'form': form})

testimoni/views.py
from django.shortcuts import render, redirect
from .models import Curhat
from django.core.exceptions import ValidationError
# from .forms import CurhatForm

# Create your views here.
def testimoni(request):
    context = {}
    if request.method == "POST":
        nama = request.POST.get('nama')
        testi = request.POST.get('testi')
        curhat = Curhat(nama=nama, testi=testi)
        try:
            curhat.clean()
            curhat.save()
        except ValidationError:
            pass
    context['curhatan'] = Curhat.objects.all() 
    return render(request, "testimoni.html", context)

homepage/templates/homepage.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>CurhatMe</title>
    <!-- <link rel="shortcut icon" type="image" href="bunga-min.png"/> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href="{% static 'css/curhat.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Patua+One|Roboto+Slab&display=swap" rel="stylesheet">
</head>

<body class="home">
    <div class="row align-items-center">
        <div class="col-md-5">
            <img id="logo" src="{% static 'images/logo.png' %}">
        </div> 
        <div class="col-md-7">
            <p id="tagline">Teman curhat <br>yang selalu ada</p>
            <a href="{% url 'homepage:reply' %}"><button type="button" class="btn btn-secondary btn-sm" id="yuk">yuk curhat</button></a>
        </div>
    </div>
</body>

homepage/templates/postreply.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>CurhatMe</title>
    <!-- <link rel="shortcut icon" type="image" href="bunga-min.png"/> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href="{% static 'css/curhat.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Patua+One|Roboto+Slab&display=swap" rel="stylesheet">
</head>

<body>
    <div class="article">
        {% comment %} <a href="{% url 'homepage:postreply' %}"></a> {% endcomment %}
            <div class="row">
                {% for i in postreply %}
                    <div class="col-sm-4 text-center">
                        <div class = "container reply">
                            <p>{{ i.reply  }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
    </div>

    {% comment %} <div class = 'col-md-12'>
        <div class = 'form-group'>
            <div class='text-center'>
                <a href="{% url 'homepage:reply' %}"><button type="button" class="btn btn-secondary btn-sm">Reply</button></a>
            </div>
        </div>
    </div> {% endcomment %}
</body>

homepage/templates/reply.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>CurhatMe</title>
    <!-- <link rel="shortcut icon" type="image" href="bunga-min.png"/> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type = "text/css" href="{% static 'css/curhat.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Patua+One|Roboto+Slab&display=swap" rel="stylesheet">
</head>

<body>
    
    <form action="{% url 'homepage:reply' %}" method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                <label id="labelreply" for="id_reply">Mau balas apa?</label>
                    {% for fields in form %}
                    <br>
                    {{ fields }}
                    {% endfor %}
                <input type="submit" class="btn btn-secondary btn-sm" value="reply" id="balas"></button>
            </div>
        </div>
    </form>
</body>

testimoni/templates/testimoni.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% load staticfiles %}
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" type="text/css" href="{% static 'css/navstyle.css' %}"/>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <link href='https://fonts.googleapis.com/css?family=Amiko' rel='stylesheet'>
        <script src="{% static 'js/parallax.min.js' %}"></script>

        <title>Curhatme | Testimoni!</title>
    </head>
    <body background="{% static 'images/bg.jpg' %}">
        <nav class="navbar navbar-fixed-top navbar-expand-lg navbar-light bg-custom">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'images/logo.png' %}" width="85" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav justify-content-center d-flex flex-fill">
                        <li class="nav-item active">
                            <a class="nav-link  navbar-center" href="#"><img src="{% static 'images/write.png' %}" width="50"></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <section class="grid isi text-center" id="curhat">
            <div class="container-fluid kontener">
                <div class="row aja">
                    <div class="col-md-12 thegrid">
                        <h1> Bagikan Pengalaman Menyenangkanmu!
                        </h1>
                    </div>
                    <div class="col-md-12 thegridmid">
                        <form action="" method="POST">
                            {% csrf_token %}
                        <!-- Button trigger modal -->
                        <button type="button" class="btn depan" data-toggle="modal" data-target="#exampleModalCenter">
                            Berikan Testimoni!
                        </button>
                        <!-- Modal -->
                        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalCenterTitle">Berikan Testimoni</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p class="judulnama"> Nama Kamu (atau tulis Anonymous): </p>
                                        <input name="nama" class="nama" type="textarea" placeholder="Siapa saya?">
                                        <p class="judultesti"> Testimoni: </p>
                                        <input name="testi" class="testi" type="textarea" placeholder="CurhatMe sangat membantu...">
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="button submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% for curhat in curhatan %}
                    <div class="col-md-8 offset-4 thegridbottom">
                        <p class="tomblo">
                        Nama      : {{ curhat.nama  }}<br>
                        Testimoni : {{ curhat.testi }} <br>
                        </p>
                    </div>
                    {% endfor %}            
                    </div>
                </div>
            </form>
        </section>
    </body>
</html>